<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>12.0</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\LogicScope.Core\LogicScope.Core.csproj" />
    <ProjectReference Include="..\LogicScope.Decode\LogicScope.Decode.csproj" />
    <PackageReference Include="ZstdSharp.Port" Version="0.8.6" />
  </ItemGroup>
</Project>
