<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <PlatformTarget>x64</PlatformTarget>
    <UseWPF>true</UseWPF>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>12.0</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\LogicScope.Core\LogicScope.Core.csproj" />
    <ProjectReference Include="..\LogicScope.Hardware\LogicScope.Hardware.csproj" />
    <ProjectReference Include="..\LogicScope.Decode\LogicScope.Decode.csproj" />
    <ProjectReference Include="..\LogicScope.Export\LogicScope.Export.csproj" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="SkiaSharp.Views.WPF" Version="2.88.9" />
    <PackageReference Include="SkiaSharp.NativeAssets.Win32" Version="2.88.9" />
  </ItemGroup>
</Project>
