[platformio]
default_envs = teensy41

[env:teensy41]
platform = teensy
board = teensy41
framework = arduino
build_flags =
  -std=gnu++17
  -DUSB_SERIAL
  -DLOGICSCOPE_FIRMWARE_VERSION_MAJOR=1
  -DLOGICSCOPE_FIRMWARE_VERSION_MINOR=0
  -DLOGICSCOPE_FIRMWARE_VERSION_PATCH=0
monitor_speed = 115200
